name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Vite requires Node.js >= 20.19.0 (or >=22.12.0). Use 20.19.0 for CI compatibility.
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

      - name: Preview and smoke-test
        run: |
          # start preview in background then test the URL
          npm run preview -- --port 4173 &
          PREVIEW_PID=$!
          sleep 2
          # try up to 5 times to allow server to start
          for i in {1..5}; do
            if curl -f http://localhost:4173/Limpopo-Connect-/ >/dev/null 2>&1; then
              echo "smoke test passed"
              break
            fi
            sleep 1
          done
          kill "$PREVIEW_PID" || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          # set custom domain for Pages
          cname: limpopoconnect.site
